### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by papb**

### CODE REVIEW

**Comment by timbru31** [comment]
No, we don't use python that much at work for projects or CI. What software do you need besides python?

**Comment by papb** [comment]
@timbru31 I just wanted python 3, node 12 and java 8 (and bash, curl and wget).

**Comment by timbru31** [comment]
You could just use this image as your base and install python3 via apt/apk.

**Comment by papb** [comment]
@timbru31 Yep, I did that :+1: Thank you very much once again!!

**Pull request merged**
