### PR TITLE
Node.js v10 Support

### PR DESCRIPTION
**Pull request by MattMorgis**
Node.js v10 will enter LTS on October 30, 2018. 

This upgrades Node.js v8 to v10 in this image. 

I'm somewhat new to the Docker ecosystem. I'm not sure if this should be versioned as to not break anyone downstream using the image. It'd be especially cool if you can specify which version of Node.js you'd want:

Ex. 

`FROM timbru31/java-node:8`
`FROM timbru31/java-node:10`

Happy to update the PR to something like this if it's possible. Just not exactly sure how 😄

### CODE REVIEW

**Comment by timbru31** [comment]
Hi Matt,

thank you very much for the PR!  
The goal is definitely to upgrade to Node.js v10. I'd like to wait though, until the Alpine variant is available, too - to keep all images as equivalent as possible.

Regarding the breaking change: I'm unsure if this would be a problem, since Node.js v10 should work fine where Node.js v8 was used before. At least nobody complained when I upgraded from 6 to 8 😂

**Comment by timbru31** [comment]
The time has come and Node.js 10 is now the LTS. I'll monitor when the official docker images for Dubnium (LTS 10 codename) and Alpine are available.

**Comment by timbru31** [comment]
Thank you very much for this PR 👍

**Comment by MattMorgis** [comment]
Awesome!

**Pull request merged**
